version: "3"
services:
  server:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_BASE=/dozzle
      - DOZZLE_USERNAME=
      - DOZZLE_PASSWORD=
      - DOZZLE_KEY=